#!/usr/bin/env bash
set -e

filesToFormat=$(
  git --no-pager diff --name-status --no-color --cached | \
    awk '$1 != "D" && $2 ~ /\.py/ {print $NF}'
)

for path in $filesToFormat
do
  black --quiet $path
  git add $path
done;
